using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CayoLoader
{
    internal static class LodList
    {
        public static string[] SLODsMain { get; } = new string[]
        {
            "hei_dt1_lod",
            "hei_hw1_lod",
            "hei_cs1_lod",
            "hei_cs1_lod2",
            "hei_cs1_lod3",
            "hei_cs2_lod",
            "hei_cs2_lod2",
            "hei_cs3_lod",
            "hei_cs4_lod",
            "hei_cs5_lod",
            "hei_cs6_lod",
            "hei_ch1_lod",
            "hei_ch2_lod",
            "hei_ch2_lod2",
            "hei_ch2_lod3",
            "hei_ch2_lod4",
            "hei_ch3_lod",
            "hei_ss1_lod",
            "hei_sc1_lod",
            "hei_sp1_lod",
            "hei_sm_lod",
            "hei_id1_lod",
            "hei_id2_lod",
            "hei_bh1_lod",
            "hei_vb_lod",
            "hei_po1_lod",
            "hei_ap1_lod",
            "hei_kt1_lod",
        };

        public static string[] SLODsIsland { get; } = new string[]
        {
            "h4_islandx_terrain_props_06_c_slod",
            "h4_islandx_terrain_props_06_b_slod",
            "h4_islandx_terrain_props_06_a_slod",
            "h4_islandx_terrain_props_05_f_slod",
            "h4_islandx_terrain_props_05_e_slod",
            "h4_islandx_terrain_props_05_d_slod",
            "h4_islandx_terrain_06_slod",
            "h4_islandx_terrain_05_slod",
            "h4_islandx_terrain_04_slod",
            "h4_islandx_terrain_02_slod",
            "h4_islandx_terrain_01_slod",
            "h4_sw_ipl_09_slod",
            "h4_sw_ipl_08_slod",
            "h4_sw_ipl_07_slod",
            "h4_sw_ipl_06_slod",
            "h4_sw_ipl_05_slod",
            "h4_sw_ipl_04_slod",
            "h4_sw_ipl_03_slod",
            "h4_sw_ipl_02_slod",
            "h4_sw_ipl_01_slod",
            "h4_sw_ipl_00_slod",
            "h4_se_ipl_09_slod",
            "h4_se_ipl_08_slod",
            "h4_se_ipl_07_slod",
            "h4_se_ipl_06_slod",
            "h4_se_ipl_05_slod",
            "h4_se_ipl_04_slod",
            "h4_se_ipl_03_slod",
            "h4_se_ipl_02_slod",
            "h4_se_ipl_01_slod",
            "h4_se_ipl_00_slod",
            "h4_nw_ipl_09_slod",
            "h4_nw_ipl_08_slod",
            "h4_nw_ipl_07_slod",
            "h4_nw_ipl_06_slod",
            "h4_nw_ipl_05_slod",
            "h4_nw_ipl_04_slod",
            "h4_nw_ipl_03_slod",
            "h4_nw_ipl_02_slod",
            "h4_nw_ipl_01_slod",
            "h4_nw_ipl_00_slod",
            "h4_ne_ipl_09_slod",
            "h4_ne_ipl_08_slod",
            "h4_ne_ipl_07_slod",
            "h4_ne_ipl_06_slod",
            "h4_ne_ipl_05_slod",
            "h4_ne_ipl_04_slod",
            "h4_ne_ipl_03_slod",
            "h4_ne_ipl_02_slod",
            "h4_ne_ipl_01_slod",
            "h4_ne_ipl_00_slod",
            "h4_islandx_mansion_slod",
            "h4_islandx_mansion_props_slod",
            "h4_islandx_mansion_b_slod",
            "h4_islandx_maindock_slod",
            "h4_islandx_maindock_props_slod",
            "h4_islandx_maindock_props_2_slod",
            "h4_islandx_checkpoint_props_slod",
            "h4_islandx_barrack_props_slod",
            "h4_islandxtower_veg_slod",
            "h4_islandxtower_slod",
            "h4_islandxdock_slod",
            "h4_islandxdock_props_slod",
            "h4_islandxdock_props_2_slod",
            "h4_islandxcanal_props_slod",
            "h4_islandairstrip_slod",
            "h4_islandairstrip_props_slod",
            "h4_islandairstrip_propsb_slod",
            "h4_islandairstrip_hangar_props_slod",
            "h4_beach_slod",
            "h4_beach_props_slod",
        };
    }
}
